# Generated by Django 4.0.5 on 2022-07-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0003_alter_cancion_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
